### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by StephanBroYT** [xKARASb/SferumBot#12]
Было бы отлично если пофиксили, а так нашел костыль что можно в generate_tg_message text обвести ```вот так```
```aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'```

**Comment by xKARASb** [comment]
К сожалению, не получилось воспроизвести ошибку, можете рассказать ваши действия или какое сообщение вы отправляли?

**Comment by StephanBroYT** [comment]
Бота поставил сначала работало, потом перестало, возможно потому-что оно отправляется в канал.
Было бы удобно если время в логах писало и при ошибке данные с api.
Полные логи:
```
INFO:root:[MAIN] raw_msg: from НазваниеЧата: А батарейки принести?, chat id: 2000000001
INFO:root:{'items': [{'date': 1732472142, 'from_id': 855357288, 'id': 699, 'version': 10001358, 'out': 0, 'important': False, 'is_hidden': False, 'attachments': [], 'conversation_message_id': 306, 'fwd_messages': [], 'text': 'А батарейки принести?', 'is_mentioned_user': False, 'peer_id': 2000000001, 'random_id': 0}], 'profiles': [{'id': 855357288, 'first_name': 'Имя', 'last_name': 'Фамилия', 'can_access_closed': True, 'is_closed': False}], 'title': 'НазваниеЧата'}
ERROR:root:Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "/root/SferumBot/main.py", line 50, in main
    await send_message(bot, msg, tg_chat_id)
  File "/root/SferumBot/tg/methods/send_message.py", line 55, in send_message
    message: Message = await message[1](bot, tg_chat_id, **message[0])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/aiogram/client/bot.py", line 2823, in send_message
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/aiogram/client/bot.py", line 492, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py", line 178, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'
INFO:root:[MAIN] raw_msg: from НазваниеЧата: А батарейки принести?, chat id: 2000000001
ERROR:root:list index out of range
Traceback (most recent call last):
  File "/root/SferumBot/main.py", line 33, in main
    message = get_message(access_token, pts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/vk/methods/get_message.py", line 24, in get_message
    peer_type = req["response"]["conversations"][-1]["peer"]["type"]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

**Comment by StephanBroYT** [comment]
Он жалуется на любой нестандартный символ по типу =-+~>< итд.

**Comment by StephanBroYT** [comment]
https://github.com/xKARASb/SferumBot/pull/17 @xKARASb

**Comment by iamlostshe** [comment]
Ошибка происходит из-за включенного в файле:

```
SferumBot/tree/main/tg/methods/send_message.py
```

свойства "MarkdownV2".

**Comment by xKARASb** [comment]
fixed
