### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by xtclovver** [xKARASb/SferumBot#16]
Traceback (most recent call last):
  File "/home/ubuntu/sferumgovno/SferumBot/startup.py", line 18, in <module>
    tg_topic_id = int(getenv("TG_TOPIC_ID"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

Если .env добавить TG_TOPIC_ID и указать свой tg id, то при пересылке сообщений ничего не работает, что делать?

**Comment by xtclovver** [comment]
А так же warning: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

**Comment by iamlostshe** [comment]
> Traceback (most recent call last): File "/home/ubuntu/sferumgovno/SferumBot/startup.py", line 18, in tg_topic_id = int(getenv("TG_TOPIC_ID")) ^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

Ошибка указывает на то, что не указан **TG_TOPIC_ID** в **.env**.

> Если .env добавить TG_TOPIC_ID и указать свой tg id, то при пересылке сообщений ничего не работает, что делать?

Все остальные поля заполнены?

**Comment by iamlostshe** [comment]
> warning: DeprecationWarning: There is no current event loop
loop = asyncio.get_event_loop()

Это не ошибка, а лишь предупреждение, о том что метод **asyncio.get_event_loop()** устарел и в будущем может быть удалён.

**Comment by xtclovver** [comment]
> Все остальные поля заполнены?

Да, все остальные заполненеы



> > warning: DeprecationWarning: There is no current event loop
> > loop = asyncio.get_event_loop()
> 
> Это не ошибка, а лишь предупреждение, о том что метод **asyncio.get_event_loop()** устарел и в будущем может быть удалён.

На всякий случай упомянул

**Comment by xtclovver** [comment]
В логах:
ERROR:asyncio:Unclosed client session

client_session: <aiohttp.client.ClientSession object at 0x00000201A77E15D0>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000201A77470E0>, 10254.421)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000201A77E1B10>
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): web.vk.me:443
DEBUG:urllib3.connectionpool:https://web.vk.me:443 "GET /?act=web_token&app_id=8202606 HTTP/1.1" 200 465
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /method/messages.getLongPollServer?v=5.223 HTTP/1.1" 200 135
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Loop starting
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim801407857 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
INFO:root:Closing loop...
INFO:root:Loop closed
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at C:\Users\xtc\PycharmProjects\SferumBot\main.py:10> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "C:\Users\xtc\PycharmProjects\SferumBot\startup.py", line 33, in <module>
    loop.run_forever()
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\xtc\PycharmProjects\SferumBot\main.py", line 20, in main
    req = requests.post(f"https://{server}", data=data).json()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\PycharmProjects\SferumBot\.venv\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\PycharmProjects\SferumBot\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\PycharmProjects\SferumBot\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\PycharmProjects\SferumBot\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\PycharmProjects\SferumBot\.venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\xtc\PycharmProjects\SferumBot\.venv\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\PycharmProjects\SferumBot\.venv\Lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\PycharmProjects\SferumBot\.venv\Lib\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1314, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xtc\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1166, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
INFO:root:Loop starting
INFO:root:Loop starting

**Comment by xKARASb** [comment]
Привет, спасибо что написал про ошибку, можешь использовать git pull, ошибку исправил!
