### ISSUE TITLE
Неработает

### ISSUE THREAD

**Issue by SECTOR-GAZA** [xKARASb/SferumBot#2]

**Comment by SECTOR-GAZA** [comment]
ubuntu 18.04 + python 3.11.5

(venv) (base) mac@mac-desktop:~/Python-3.11.7/SferumBot$ python3 -m main
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/mac/Python-3.11.7/SferumBot/main/__init__.py", line 10, in <module>
    from .main import main
  File "/home/mac/Python-3.11.7/SferumBot/main/main.py", line 9, in <module>
    from tgBot.methods import send_message
  File "/home/mac/Python-3.11.7/SferumBot/tgBot/__init__.py", line 10, in <module>
    host_id = int(getenv("TG_USER_ID"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
(venv) (base) mac@mac-desktop:~/Python-3.11.7/SferumBot$ python3 -m main
