### ISSUE TITLE
ERROR:root:'chat_settings'

### ISSUE THREAD

**Issue by toperx** [xKARASb/SferumBot#5]
Hi! 
How to fix this?

```python
INFO:root:Loop starting
INFO:root:[MAIN] raw_msg: from  ... : ping_piping, chat id: 999999999
ERROR:root:'chat_settings'
Traceback (most recent call last):
  File "/root/SferumBot/main.py", line 33, in main
    message = get_message(access_token, pts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/vk/methods/get_message.py", line 26, in get_message
    "title": req["response"]["conversations"][-1]["chat_settings"]["title"]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'chat_settings'
```

**Comment by xKARASb** [comment]
Hello, can you provide debug logs? (You must change `level=logging.INFO` to level=`logging.UNSET`) In these case, we can see full response from VK

**Comment by toperx** [comment]
> Hello, can you provide debug logs? (You must change `level=logging.INFO` to level=`logging.NOTSET` in `startup.py` at 15 line) In these case, we can see full response from VK

Ok

```python
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): web.vk.me:443
DEBUG:urllib3.connectionpool:https://web.vk.me:443 "GET /?act=web_token&app_id=8202606 HTTP/1.1" 200 462
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /method/messages.getLongPollServer?v=5.223 HTTP/1.1" 200 136
DEBUG:asyncio:Using selector: EpollSelector
INFO:root:Loop starting
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 80
INFO:root:[MAIN] raw_msg: from  ... : tezzzd, chat id: 999999999
DEBUG:root:[MAIN] allowed chat
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /method/messages.getLongPollHistory?v=5.223 HTTP/1.1" 200 500
DEBUG:root:[VK API] get_message response: {'response': {'history': [[4, 1213, 3, 999999999]], 'messages': {'count': 1, 'items': [{'date': 1711453439, 'from_id': 111111111, 'id': 1213, 'out': 1, 'version': 10003
481, 'attachments': [], 'conversation_message_id': 18, 'fwd_messages': [], 'important': False, 'is_hidden': False, 'peer_id': 999999999, 'random_id': -2056455702, 'text': 'tezzzd', 'is_mentioned_user': False}]}
, 'profiles': [{'id': 999999999, 'first_name': 'UserNa', 'last_name': 'UserSa', 'can_access_closed': True, 'is_closed': False}, {'id': 111111111, 'first_name': 'UserNb', 'last_name': 'UserSb', 'can_access_close
d': True, 'is_closed': False}], 'new_pts': 10003481, 'from_pts': 10003480, 'conversations': [{'peer': {'id': 999999999, 'type': 'user', 'local_id': 999999999}, 'last_message_id': 1213, 'last_conversation_messag
e_id': 18, 'in_read': 1213, 'out_read': 1212, 'in_read_cmid': 18, 'out_read_cmid': 17, 'version': 10003481, 'sort_id': {'major_id': 0, 'minor_id': 1213}, 'is_marked_unread': False, 'important': False, 'can_writ
e': {'allowed': True}, 'can_send_money': False, 'can_receive_money': False, 'peer_flags': 0}]}}
ERROR:root:'chat_settings'
Traceback (most recent call last):
  File "/root/SferumBot/main.py", line 33, in main
    message = get_message(access_token, pts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/vk/methods/get_message.py", line 26, in get_message
    "title": req["response"]["conversations"][-1]["chat_settings"]["title"]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'chat_settings'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
INFO:root:Closing loop...
INFO:root:Loop closed
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /root/SferumBot/main.py:10> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/root/SferumBot/startup.py", line 32, in <module>
    loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/SferumBot/main.py", line 20, in main
    req = requests.post(f"https://{server}", data=data).json()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1311, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

```

**Comment by xKARASb** [comment]
You sure you get message from group chat? Not from DM. But DM support is also interesting, i`ll add soon.

**Comment by xKARASb** [comment]
Check new commit! Try it now.

**Comment by toperx** [comment]
Ok

```python
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): web.vk.me:443
DEBUG:urllib3.connectionpool:https://web.vk.me:443 "GET /?act=web_token&app_id=8202606 HTTP/1.1" 200 463
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /method/messages.getLongPollServer?v=5.223 HTTP/1.1" 200 136
DEBUG:asyncio:Using selector: EpollSelector
INFO:root:Loop starting
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 79
INFO:root:[MAIN] raw_msg: from  ... : test1, chat id: 999999999
DEBUG:root:[MAIN] allowed chat
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /method/messages.getLongPollHistory?v=5.223 HTTP/1.1" 200 499
DEBUG:root:[VK API] get_message response: {'response': {'history': [[4, 1215, 3, 999999999]], 'messages': {'count': 1, 'items': [{'date': 1711493197, 'from_id': 111111111, 'id': 1215, 'out': 1, 'version': 10003486, 'attachments': [], 'conversation_message_id': 20, 'fwd_messages': [], 'important': False, 'is_hidden': False, 'peer_id': 999999999, 'random_id': -2096213527, 'text': 'test1', 'is_mentioned_user': False}]}, 'profiles': [{'id': 999999999, 'first_name': 'UserNa', 'last_name': 'UserSа', 'can_access_closed': True, 'is_closed': False}, {'id': 111111111, 'first_name': 'UserNb', 'last_name': 'UserSb', 'can_access_closed': True, 'is_closed': False}], 'new_pts': 10003486, 'from_pts': 10003485, 'conversations': [{'peer': {'id': 999999999, 'type': 'user', 'local_id': 999999999}, 'last_message_id': 1215, 'last_conversation_message_id': 20, 'in_read': 1215, 'out_read': 1214, 'in_read_cmid': 20, 'out_read_cmid': 19, 'version': 10003486, 'sort_id': {'major_id': 0, 'minor_id': 1215}, 'is_marked_unread': False, 'important': False, 'can_write': {'allowed': True}, 'can_send_money': False, 'can_receive_money': False, 'peer_flags': 0}]}}
ERROR:root:'type'
Traceback (most recent call last):
  File "/root/SferumBot/main.py", line 33, in main
    message = get_message(access_token, pts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/vk/methods/get_message.py", line 24, in get_message
    if req["response"]["conversations"][-1]["type"] == "user":
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 71
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 48
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 87
INFO:root:[MAIN] raw_msg: from  ... : 🐝, chat id: 999999999
DEBUG:root:[MAIN] allowed chat
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /method/messages.getLongPollHistory?v=5.223 HTTP/1.1" 200 560
DEBUG:root:[VK API] get_message response: {'response': {'history': [[4, 1215, 3, 999999999], [7, 999999999, 1215], [4, 1216, 1, 999999999]], 'messages': {'count': 2, 'items': [{'date': 1711493197, 'from_id': 111111111, 'id': 1215, 'out': 1, 'version': 10003488, 'attachments': [], 'conversation_message_id': 20, 'fwd_messages': [], 'important': False, 'is_hidden': False, 'peer_id': 999999999, 'random_id': -2096213527, 'text': 'test1', 'is_mentioned_user': False}, {'date': 1711493229, 'from_id': 999999999, 'id': 1216, 'out': 0, 'version': 10003488, 'attachments': [], 'conversation_message_id': 21, 'fwd_messages': [], 'important': False, 'is_hidden': False, 'peer_id': 999999999, 'random_id': 0, 'text': '🐝', 'is_mentioned_user': False}]}, 'profiles': [{'id': 999999999, 'first_name': 'UserNa', 'last_name': 'UserSа', 'can_access_closed': True, 'is_closed': False}, {'id': 111111111, 'first_name': 'UserNb', 'last_name': 'UserSb', 'can_access_closed': True, 'is_closed': False}], 'new_pts': 10003488, 'from_pts': 10003485, 'conversations': [{'peer': {'id': 999999999, 'type': 'user', 'local_id': 999999999}, 'last_message_id': 1216, 'last_conversation_message_id': 21, 'in_read': 1215, 'out_read': 1216, 'in_read_cmid': 20, 'out_read_cmid': 21, 'version': 10003488, 'sort_id': {'major_id': 0, 'minor_id': 1216}, 'unread_count': 1, 'is_marked_unread': False, 'important': False, 'can_write': {'allowed': True}, 'can_send_money': False, 'can_receive_money': False, 'peer_flags': 536870912}]}}
ERROR:root:'type'
Traceback (most recent call last):
  File "/root/SferumBot/main.py", line 33, in main
    message = get_message(access_token, pts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/vk/methods/get_message.py", line 24, in get_message
    if req["response"]["conversations"][-1]["type"] == "user":
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 87
INFO:root:[MAIN] raw_msg: from  ... : 🐝, chat id: 999999999
DEBUG:root:[MAIN] allowed chat
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /method/messages.getLongPollHistory?v=5.223 HTTP/1.1" 200 560
DEBUG:root:[VK API] get_message response: {'response': {'history': [[4, 1215, 3, 999999999], [7, 999999999, 1215], [4, 1216, 1, 999999999]], 'messages': {'count': 2, 'items': [{'date': 1711493197, 'from_id': 111111111, 'id': 1215, 'out': 1, 'version': 10003488, 'attachments': [], 'conversation_message_id': 20, 'fwd_messages': [], 'important': False, 'is_hidden': False, 'peer_id': 999999999, 'random_id': -2096213527, 'text': 'test1', 'is_mentioned_user': False}, {'date': 1711493229, 'from_id': 999999999, 'id': 1216, 'out': 0, 'version': 10003488, 'attachments': [], 'conversation_message_id': 21, 'fwd_messages': [], 'important': False, 'is_hidden': False, 'peer_id': 999999999, 'random_id': 0, 'text': '🐝', 'is_mentioned_user': False}]}, 'profiles': [{'id': 999999999, 'first_name': 'UserNa', 'last_name': 'UserSbа', 'can_access_closed': True, 'is_closed': False}, {'id': 111111111, 'first_name': 'UserNb', 'last_name': 'UserSb', 'can_access_closed': True, 'is_closed': False}], 'new_pts': 10003488, 'from_pts': 10003485, 'conversations': [{'peer': {'id': 999999999, 'type': 'user', 'local_id': 999999999}, 'last_message_id': 1216, 'last_conversation_message_id': 21, 'in_read': 1215, 'out_read': 1216, 'in_read_cmid': 20, 'out_read_cmid': 21, 'version': 10003488, 'sort_id': {'major_id': 0, 'minor_id': 1216}, 'unread_count': 1, 'is_marked_unread': False, 'important': False, 'can_write': {'allowed': True}, 'can_send_money': False, 'can_receive_money': False, 'peer_flags': 536870912}]}}
ERROR:root:'type'
Traceback (most recent call last):
  File "/root/SferumBot/main.py", line 33, in main
    message = get_message(access_token, pts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/vk/methods/get_message.py", line 24, in get_message
    if req["response"]["conversations"][-1]["type"] == "user":
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 40
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 98
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 80
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 59
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 40
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
DEBUG:urllib3.connectionpool:https://api.vk.me:443 "POST /ruim111111111 HTTP/1.1" 200 32
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.vk.me:443
INFO:root:Closing loop...
INFO:root:Loop closed
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /root/SferumBot/main.py:10> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/root/SferumBot/startup.py", line 32, in <module>
    loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/SferumBot/main.py", line 20, in main
    req = requests.post(f"https://{server}", data=data).json()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/root/SferumBot/venv/lib/python3.11/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1311, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

```
