### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by megamix123** [xKARASb/SferumBot#7]
При запуске бота выдаёт ошибки
`Traceback (most recent call last):
  File "d:\Developing\SferumBot\startup.py", line 11, in <module>
    from main import main
  File "d:\Developing\SferumBot\main.py", line 7, in <module>
    from tg.methods import send_message
  File "d:\Developing\SferumBot\tg\__init__.py", line 1, in <module>
    from .bot import start_polling
  File "d:\Developing\SferumBot\tg\bot.py", line 10, in <module>
    host_id = int(getenv("TG_USER_ID"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
!`[image](https://github.com/xKARASb/SferumBot/assets/60653600/f20d41f8-5478-43e8-aec6-0e3036aacb8a)

**Comment by R1senDev** [comment]
https://github.com/xKARASb/SferumBot?tab=readme-ov-file#setup-env-file

Did it help?
